#!/usr/bin/env bash
# Usage: proj python
# Summary: create a new python project directory
# Help:
#
source "$_PROJ_ROOT/lib/proj_functions"

banner

if [ -z "$1" ] && [ -z "$2" ]; then
  die '$1 should be the name of your project $2 should be the python version number'
fi

###########################################################
# check required params
APP=$1
VERSION=$2

###########################################################
action "create project directory"
  mkdir $APP
ok

###########################################################
action "create virtual environment"
  pyenv virtualenv $VERSION
ok

###########################################################
action "initialize"
  echo "$VERSION" > $APP/.python-version
  echo "$APP" > $APP/.python-virtualenv
ok

# pyenv install 2.7.11
# pyenv install 3.5.1
# pyenv rehash

# # list virtualenvs
# pyenv virtualenvs

# # create a new virtualenv
# pyenv virtualenv $APP

# # destroy a  virtualenv
# pyenv uninstall $APP

# # create a directory switch for a virtualenv
# pyenv local $APP

exit
