#!/usr/bin/env bash
# Usage: proj node
# Summary: create a new nodejs project directory
# Help:
#
source "$_PROJ_ROOT/lib/proj_functions"
set -e

banner

###########################################################
# check required params
APP=$1
VERSION=$2

###########################################################
action "create project directory"
ok

###########################################################
action "create virtual environment"
ok

###########################################################
action "initialize"
ok

# create project directory
# create .nvmrc file
# create package.json

exit
