#!/usr/bin/env bash
# Usage: proj node
# Summary: create a new nodejs project directory
# Help:
#
source "$_PROJ_ROOT/lib/proj_functions"
set -e

banner

if [ -z "$1" ] && [ -z "$2" ]; then
  die '$1 should be the name of your project $2 should be the node version number'
fi

###########################################################
# check required params
APP=$1
VERSION=$2

###########################################################
action "create project directory"
  mkdir $APP
ok

###########################################################
action "initialize"
  touch $APP/.env
  echo "nvm use $VERSION
export OLDPATH=\$PATH
export PATH=`pwd`/node_modules/.bin:\$PATH
" > $APP/.env

  touch $APP/.out
  echo "
nvm use system
export PATH=\$OLDPATH
" > $APP/.out
ok

cd $APP
npm init

# create .nvmrc file

exit
