#!/usr/bin/env bash
# Usage: proj sub
# Summary: create a new subcommand project directory
# Help:
#
source "$_PROJ_ROOT/lib/proj_functions"
set -e

banner

action "create project directory"
ok

action "clone subcommand repo"
ok

action "initialize sub"
ok

exit
