#!/usr/bin/env bash
# Usage: proj java
# Summary: create a new java project directory
# Help:
#
source "$_PROJ_ROOT/lib/proj_functions"
set -e

banner

if [ -z "$1" ] && [ -z "$2" ]; then
  die '$1 should be the name of your project $2 should be the java version number'
fi

###########################################################
# check required params
APP=$1
VERSION=$2

###########################################################
action "create project directory"
ok

###########################################################
action "create virtual environment"
ok

###########################################################
action "initialize"
ok

exit
