#!/usr/bin/env bash
# Usage: proj java
# Summary: write a summary for your new proj command
# Help: This will print out when you run proj help java
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_PROJ_ROOT/lib/proj_functions"
set -e

banner

###########################################################
# check required params
APP=$1
VERSION=$2

###########################################################
action "create project directory"
ok

###########################################################
action "create virtual environment"
ok

###########################################################
action "initialize"
ok

exit
