#!/usr/bin/env bash
# Usage: pibox new
# Summary: scaffold a new command for proj
# Help: This will print out when you run `proj help new`.
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_PROJ_ROOT/lib/proj_functions"
set -e

banner

bot "Creating new proj command"

if [[ $# -eq 0 ]] ; then
  error 'please provide a name for your new proj command'
  die 
fi

command_file="$_PROJ_ROOT/libexec/proj-$1"
if [ -s "$command_file" ]
  then 
    die "COMMAND EXISTS"
  else
    action "create $command_file"
    touch $command_file
    chmod a+x $command_file
    echo "$TEMPLATE" > $command_file
    ok
fi

die 
